name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install repo requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Run tests
        run: |
          pip install pytest
          pytest -q
      - name: Install Node & CDK
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install CDK
        run: |
          npm install -g aws-cdk@2
      - name: CDK Synth
        run: |
          cd infra
          python -m pip install -r requirements.txt
          cdk synth
